### ISSUE TITLE
install-mongdb fails on osx, bad architecture

### ISSUE THREAD

**Issue by dmacd** [mongolab/mongoctl#9] opened 2013-07-08 22:19 UTC
It looks like its trying to fetch a nonexistent i386 version

dmacd$ mongoctl install 2.2.5

Running install for osx 32bit to mongoDBInstallationsDirectory (/Users/dmacd/mongodb)...
ERROR: Unable to download from url 'http://fastdl.mongodb.org/osx/mongodb-osx-i386-2.2.5.tgz' (response code '403'). It could be that version '2.2.5' you specified does not exist. Please double check the version you provide

Running the python 2.7.5 build from python.org.

Would love to use your tool, is there any way to provide a literal url?

**Comment by abdulito** [comment] 2015-04-10 15:49
Cannot reproduce. Closing. Please create a new issue if you are still seeing this. Thanks!

**Closed by abdulito** 2015-04-10 15:49 UTC
